config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/welcome', to: 'welcome#index' 

  authenticated :user do
    root 'notes#index', as: 'authenticated_root'
  end
  root 'welcome#index'

  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    def index
        @notes = current_user.notes.order("created_at desc")
    end

    def new
        @note = current_user.notes.new
    end
    
    def create
        @note = current_user.notes.new(note_params)
        if @note.save
            redirect_to @note, alert: "Record Saved Successfully."
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @note.update(note_params)
            redirect_to @note, alert: "Record Updated Successfully."
        else
            render 'edit'
        end
    end

    def destroy
        @note.destroy
        redirect_to root_path, alert: "Record Deleted Successfully."
    end

    private
        def find_note
            @note = Note.find(params[:id])
        end

        def note_params
            params.require(:note).permit(:title, :content)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Notenote
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        = link_to image_tag('logo.svg'), root_path, id: "logo"
        %nav
          - if user_signed_in?
            = link_to "New Note", new_note_path
            = link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            = link_to "Login", user_session_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

app/views/notes/edit.html.haml
%h1 Edit a Note
= render 'form'
%br/
= link_to "Cancel", @note

app/views/notes/index.html.haml
.wrapper_with_padding
    #notes.clearfix
        -unless @notes.blank?
            - @notes.each do |note|
                %a{ href: (url_for [note])}
                    .note
                        %p.title= note.title
                        %p.date= time_ago_in_words(note.created_at)
        - else
            %h2 Add a note
            %p It appears you haven't created any notes yet... Lets fix that. Why don't you create a note below.
            %button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
%h1 Add new Note
= render 'form'
%br/
= link_to 'Home', root_path

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content
%br/
= link_to 'All Notes', notes_path
= link_to 'Edit', edit_note_path(@note)
= link_to 'Destroy', @note, method: :delete, data: { confirm: "Are you sure to delete?" }

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 NoteNote
        %p Your online notebook. Never forget an idea again.
        %button= link_to 'Signup', new_user_registration_path
#testimonial
    .wrapper
        %p.quote "The greatest notebook application. Period."
        %p.name Mackenzie Child
#callouts
    .callout_inner
        .wrapper
            .callout
                %h2 Notes
                %p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
            .callout
                %h2 Rocket
                %p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
            .callout
                %h2 Lightning
                %p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
#bottom_cta
    .wrapper
        %h2 For Realz!
        %p I want you to sign up... If you don't, I will find you!
        %button= link_to "Click Meee!!!", new_user_registration_path
%footer
    %p &copy;